version: '3'
services:
  express-app:
    image: 'natours-prod-img'
    build:
      context: .
      target: production
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - PORT=80
    env_file:
      - ./prod.env
    command: ['npm', 'start']

  mongo-dev:
    image: mongo
    restart: always
    env_file:
      - ./prod.env
