version: '3'
services:
  express-app:
    image: 'natours-dev-img'
    build:
      context: .
      target: builder
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src:ro
      - ./__tests__:/app/__tests__:ro
    environment:
      - NODE_ENV=devlopment
      - PORT=3000
    command: ['npm', 'run', 'dev']
